### ISSUE TITLE
Indicator: Security

### ISSUE THREAD

**Issue by lukefretwell** [civichackingagency/scangov#158]
## Description

Add security indicator.

Reference: 

* https://github.com/GSA/federal-website-index/blob/main/data/dataset/cisa_https.csv
* https://https.cio.gov/hsts/
* https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

## Specs

- Label: 
- Icon: `<i class="fa-solid fa-lock"></i>`

## Validators

| Tag | Description | Status |
|----------|----------|----------|
| HTTPS    | Tag 1    | Active/Missing    |
| HSTS    | Tag 2    | Active/Missing    |
| CSP    | Tag 2    | Active/Missing    |
| Other?    | Tag 2    | Active/Missing    |

## To-do

- [ ] Add to search filter
- [ ] Factor into 'all' scores (all domain + individual)
- [ ] Add [documentation](https://docs.scangov.org)

**Comment by Narlotl** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
